development:
  adapter: postgresql
  database: userapps
  username: app3780
  password: "_aB@R=FX7p13-"
  host: 10.251.55.79
  schema_search_path: app3780
 
production:
  development
 
test:
  adapter: postgresql
  database: userapps
  username: app3780
  password: "_aB@R=FX7p13-"
  host: 10.251.55.79
  schema_search_path: app3780_test